enabled: true

handlers:
  - com.networknt.exception.ExceptionHandler@exception
  - com.xlongwei.search.ServiceHandler@service
  - com.xlongwei.search.DistrictHandler
  - com.xlongwei.search.IndexHandler
  - com.xlongwei.search.LogserverHandler

chains:
  default:
    - exception
    - service

paths:
  - path: '/service/*'
    method: 'GET'
    exec:
      - default
  - path: '/service/*'
    method: 'POST'
    exec:
      - default


