httpPort: ${httpPort:9200}
enableHttp: true
enableHttps: false
serviceId: com.xlongwei.light-lucene
enableRegistry: false
ioThreads: ${ioThreads:2}
workerThreads: ${workerThreads:3}
alwaysSetDate: false
