singletons:
- com.networknt.server.ShutdownHookProvider:
  - com.xlongwei.search.SearchShutdown
- com.networknt.registry.URL:
  - com.networknt.registry.URLImpl:
      protocol: light
      host: localhost
      port: 8080
      path: direct
      parameters:
        com.xlongwei.light4j: ${light4j.host:http://localhost:8080}
- com.networknt.registry.Registry:
  - com.networknt.registry.support.DirectRegistry
- com.networknt.balance.LoadBalance:
  - com.networknt.balance.RoundRobinLoadBalance
- com.networknt.cluster.Cluster:
  - com.networknt.cluster.LightCluster
